Removed pre-commit linting on non-`main` branches
- our use-case for this is to ensure that people don't push to
  `main` without running linting, as this can block CI from passing
  until the linting issue is resolved
- however, it can become annoying to run linting on non-main branches,
  especially when you just want to WIP some changes without caring for
  linting
- generally speaking, anyone who creates commits on a non-main branch is
  going to open them as a PR, so linting is run anyway
- this commit get the branch name and only runs linting if we're on
  `main`

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -3,12 +3,15 @@
 
 [ -n "$CI" ] && exit 0
 
-yarn lint-staged --relative
-lintStatus=$?
+GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+if [ "$GIT_BRANCH" = "main" ]; then
+    yarn lint-staged --relative
+    lintStatus=$?
 
-if [ $lintStatus -ne 0 ]; then
-    echo "❌ Linting failed"
-    exit 1
+    if [ $lintStatus -ne 0 ]; then
+        echo "❌ Linting failed"
+        exit 1
+    fi
 fi
 
 green='\033[0;32m'
